chore: Use dimensions from dimen resources
immadisairaj/CodeforcesApp pull request #15
Opened 2019-07-03 12:45 UTC by amangoyal2339

Fixes #[Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

**Changes:**

[Add here what changes were made in this issue and if possible provide links.]

Please make sure these boxes are checked before submitting your pull request - thank you!

- [ ] Run unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into a single commit by squashing them.

Please add screenshots/GIFs here if there are any changes to the UI below.

2019-07-03 12:59 UTC, amangoyal2339 commented
![git](https://user-images.githubusercontent.com/51189244/60593458-6bd65100-9dc0-11e9-9c8e-7abd8001b51e.PNG)
This time I separately added the xml files but idea file still got added ,don't know why . please help.

2019-07-03 13:00 UTC, amangoyal2339 commented
This time I added the files separately but still idea file got added , don't know why . please help .

2019-07-03 13:12 UTC, immadisairaj commented
> This time I added the files separately but still idea file got added , don't know why . please help .

revert, add the files needed and force push into the same branch

2019-07-03 13:14 UTC, immadisairaj requested changes

2019-07-03 13:14 UTC, immadisairaj commented on app/src/main/res/layout/activity_info.xml
> +                android:layout_margin="@dimen/margin1"
do not use it as `margin1`. it has to be generalized
Not only this but all the other also

2019-07-03 13:15 UTC, immadisairaj commented
@amangoyal2339 can you please check the build log and fix the build.

2019-07-03 13:33 UTC, amangoyal2339 commented
generalized means ? can please give me an example.

On Wed, 3 Jul 2019 at 18:44, Sai Rajendra Immadi <notifications@github.com>
wrote:

> *@immadisairaj* requested changes on this pull request.
> ------------------------------
>
> In app/src/main/res/layout/activity_info.xml
> <https://github.com/immadisairaj/CodeforcesApp/pull/15#discussion_r299948779>
> :
>
> > @@ -20,72 +20,72 @@
>                  android:id="@+id/ll_info"
>                  android:layout_width="match_parent"
>                  android:layout_height="match_parent"
> -                android:layout_margin="10dp"
> +                android:layout_margin="@dimen/margin1"
>
> do not use it as margin1. it has to be generalized
> Not only this but all the other also
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/immadisairaj/CodeforcesApp/pull/15?email_source=notifications&email_token=AMGRL7BJWA3S5SANJORWFQTP5SQ23A5CNFSM4H5FNVPKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5MMR5Q#pullrequestreview-257476854>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMGRL7ABTZQGLEAJPPQULRTP5SQ23ANCNFSM4H5FNVPA>
> .
>

2019-07-03 13:42 UTC, amangoyal2339 commented
Ok so I will generalize the size not the name , Got it .
Thank you.

On Wed, 3 Jul 2019 at 19:03, Aman Goyal <amangoyaa@gmail.com> wrote:

> generalized means ? can please give me an example.
>
> On Wed, 3 Jul 2019 at 18:44, Sai Rajendra Immadi <notifications@github.com>
> wrote:
>
>> *@immadisairaj* requested changes on this pull request.
>> ------------------------------
>>
>> In app/src/main/res/layout/activity_info.xml
>> <https://github.com/immadisairaj/CodeforcesApp/pull/15#discussion_r299948779>
>> :
>>
>> > @@ -20,72 +20,72 @@
>>                  android:id="@+id/ll_info"
>>                  android:layout_width="match_parent"
>>                  android:layout_height="match_parent"
>> -                android:layout_margin="10dp"
>> +                android:layout_margin="@dimen/margin1"
>>
>> do not use it as margin1. it has to be generalized
>> Not only this but all the other also
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/immadisairaj/CodeforcesApp/pull/15?email_source=notifications&email_token=AMGRL7BJWA3S5SANJORWFQTP5SQ23A5CNFSM4H5FNVPKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5MMR5Q#pullrequestreview-257476854>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AMGRL7ABTZQGLEAJPPQULRTP5SQ23ANCNFSM4H5FNVPA>
>> .
>>
>

2019-07-04 04:59 UTC, immadisairaj approved these changes

2019-07-04 12:13 UTC, merged