Use snackbar instead of Toast
immadisairaj/CodeforcesApp pull request #17
Opened 2019-07-04 06:24 UTC by amangoyal2339

Fixes #8 
**Changes:**

Replaced the Toast with snackbar.

Please make sure these boxes are checked before submitting your pull request - thank you!

- [ ] Run unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into a single commit by squashing them.

Please add screenshots/GIFs here if there are any changes to the UI below.

2019-07-04 12:18 UTC, immadisairaj commented
@amangoyal2339 please follow semantic pr guidelines

2019-07-04 17:48 UTC, amangoyal2339 commented
@immadisairaj  please Review .

2019-07-05 15:38 UTC, immadisairaj commented
> @immadisairaj please Review .

yeah, sure. No need to ask me to review. I'll do it sometime or other.

2019-07-05 16:18 UTC, immadisairaj requested changes
can you make all the statements in a single line

2019-07-05 16:18 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/InfoActivity.java
> +                                .show();
can you move this to the above line

2019-07-05 16:18 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/InfoActivity.java
> +                                .show();
same as above

2019-07-06 16:05 UTC, immadisairaj requested changes
please try to change it in local but not directly using the github. and also squash the commits into one

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/InfoActivity.java
> +                        Snackbar.make(getWindow().getDecorView().getRootView(), handle, Snackbar.LENGTH_SHORT) .show();
remove the space near `RT) .show(`

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/InfoActivity.java
> +                Snackbar.make(getWindow().getDecorView().getRootView(), "No Internet Connection", Snackbar.LENGTH_SHORT)  .show();
same here

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/InfoActivity.java
> +                  if (countOfCalls == 0)
can you remove the leading extra space

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/InfoActivity.java
> +                    InfoActivity.super.onBackPressed();
can you remove the trailing spaces

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/SubmissionActivity.java
> +                            SubmissionActivity.super.onBackPressed();
can you please remove the extra leading and trailing spaces

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/SubmissionActivity.java
> +                    Snackbar.make(getWindow().getDecorView().getRootView(),  "Wrong handle, Try Again", Snackbar.LENGTH_SHORT) .show();
same as above

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/SubmissionActivity.java
> +                     SubmissionActivity.super.onBackPressed();
same as above

2019-07-06 16:05 UTC, immadisairaj commented on app/src/main/java/com/example/immadisairaj/codeforces/SubmissionActivity.java
> +                Snackbar.make(getWindow().getDecorView().getRootView(),  "No Internet Connection", Snackbar.LENGTH_SHORT) .show();
same as above

2019-07-08 12:47 UTC, immadisairaj commented
@amangoyal2339 why are they multiple commits. and which were already there..

can you resolve the conflicts

2019-10-02 05:44 UTC, closed without merging