Update README.md
immadisairaj/CodeforcesApp pull request #19
Opened 2019-07-04 13:02 UTC by amangoyal2339

Fixes #18 
Changes: 
Added screenshots from the app .
Please make sure these boxes are checked before submitting your pull request - thanks you!

- [ ] Run unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into a single commit by squashing them.

Please add screenshots/GIFs here if there are any changes to the UI.

2019-07-05 15:35 UTC, immadisairaj requested changes

2019-07-05 15:35 UTC, immadisairaj commented on README.md
> +  </tr>
I guess there is no need of having the same kind of pictures again. Can you please remove this.

2019-07-05 15:36 UTC, immadisairaj commented
@amangoyal2339 try to squash commits into one as this is not a big issue

2019-07-06 16:00 UTC, immadisairaj commented
> @amangoyal2339 try to squash commits into one as this is not a big issue

can you please do this

2019-07-06 16:01 UTC, immadisairaj approved these changes

2019-07-07 08:30 UTC, immadisairaj requested changes
> @amangoyal2339 try to squash commits into one as this is not a big issue

can you please do this

2019-07-08 12:44 UTC, immadisairaj commented
> * [x]  If you have multiple commits please combine them into a single commit by squashing them.

@amangoyal2339 you have checked this but still you have multiple commits

2019-07-08 13:07 UTC, amangoyal2339 commented
@immadisairaj I will squash them asap.

2019-07-08 17:58 UTC, closed without merging